### ISSUE TITLE
Publish to crates.io?

### ISSUE THREAD

**Issue by KSXGitHub** [agnipau/slap#1]
Do you plan to publish this to crates.io? Unfortunately, the name `slap` is already taken there so you would have to rename.

**Comment by guardam** [comment]
To fix the problem of the name being already taken probably the only way would be renaming the crate to `slap-cli` and the binary to `slap`. I'm going to try this and see how it goes.

**Comment by guardam** [comment]
Luckily the [[bin]] trick in Cargo.toml worked :)
