### ISSUE TITLE
Simplify installing slap

### ISSUE THREAD

**Issue by travis-bradbury** [agnipau/slap#6]
At my job, we occasionally write bash scripts. Argument parsing and dependency checking is awful, but slap looks it would inject some sanity into that process. Typically, there's a small number of people that write scripts and many more that would execute the scripts. Using cargo as slap's installation method makes it seem like slap would cause more problems for people who support the script than it solves if we need everyone to
1. Install rustup.
2. Install slap with cargo.
3. Update slap and rust occasionally.

That is, it seems like we'd gain some sanity the few times we set up argument parsing, help text, etc in scripts, but lose more than that as we debug coworkers installing and updating rustup. Maybe I'm overestimating how much work that would be.

Is it realistic to start providing binaries slap here? Then we could provide instructions like "download slap from __ and put it in $PATH" and skip rustup/cargo.

**Comment by guardam** [comment]
I completely agree with you and I'm experimenting with GitHub Actions to automate the process of compiling slap to multiple platforms. Soon it will be ready.

**Comment by guardam** [comment]
All right, now you can download pre-compiled binaries for `linux`, `linux-arm`, `macos`, `win-msvc`, `win-gnu`, `win32-msvc` [here](https://github.com/agnipau/slap/releases/tag/1.2.0)
