### ISSUE TITLE
Unsure whether `slap path` dereferences symlinks

### ISSUE THREAD

**Issue by ngirard** [agnipau/slap#9]
The ability to get the absolute path of a script using `slap path` is a valuable feature ; but after reading the README I'm unsure whether `slap path` dereferences symlinks, the more so as the non-slap command given as a comparison doesn't.

**Comment by guardam** [comment]
For now `slap path` never dereferences symlinks, the behavior is the same as `$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)`.  
Updating the README and closing this in favor of #17.

**Comment by ngirard** [comment]
Thanks for the clarification.

Not that I'm in need of this right now, but considering that it is a recurring need and it's particularly tricky to solve in a portable way, adding the ability to dereference symlinks would be a valuable addition IMHO.

**Comment by guardam** [comment]
Already added that option with agnipau/slap@0f091a9e641b43a222906dbf07d33ce7e363c2b5 :)

**Comment by ngirard** [comment]
Wow, nice !
I think it deserves a release on its own, and the README should definitely mention it !

Once this feature is shipped, hopefully I'll find the time & energy to mention it to the relevant Stack Exchange threads.

**Comment by guardam** [comment]
Now in 1.3.0
